### ISSUE TITLE
Spring: Dates always serialized as timestamps

### ISSUE THREAD

**Issue by CalamarBicefalo** [FasterXML/jackson-datatype-jsr310#26] opened 2015-06-05 15:53 UTC
After registering the module like this:

    @Bean
    public ObjectMapper objectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new JSR310Module());
        mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS,false);
        return mapper;
    }

It always deserializes dates as timestamps in this step:

    com.fasterxml.jackson.datatype.jsr310.ser.LocalDateTimeSerializer
    if (useTimestamp(provider)) { //Return true no matter what.

**Comment by zkiss** [comment] 2015-06-07 04:39
It seems you are using Spring. As far as I know, when you want Spring (4, Spring Boot) to use an `ObjectMapper` bean instance you are creating, you need to mark it as `@Primary`. So try:

```
@Bean
@Primary
public ObjectMapper objectMapper() {
    ObjectMapper mapper = new ObjectMapper();
    mapper.registerModule(new JSR310Module());
    mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS,false);
    return mapper;
}
```

In case that does not work, could you please provide a piece of code without using Spring which produces the unwanted behaviour?

**Comment by cowtowncoder** [comment] 2015-06-24 05:33
I assume this is due to Spring integration issues; closing, may reopen with a stand-alone test reproduction.

**Closed by cowtowncoder** 2015-06-24 05:33 UTC
